#!/usr/bin/env bash

echo "Creating database dummy_dash..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database dummy_dash-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://wprevost@localhost:5432/dummy_dash-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
